/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projeto04;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author laboratorio
 */
public class FormProjeto04 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormProjeto04.class.getName());
    
    public char sexo;
    public boolean astronomia, tecnologia, esportes;
    private Arquivo arquivo;
    private List<Pessoa> listaPessoas;
    private int linhaEdicao = -1;
    /**
     * Creates new form FormProjeto04
     */
    public FormProjeto04() {
        initComponents();
        arquivo = new Arquivo("pessoas");
        listaPessoas = arquivo.lerArquivo();
        carregarTabela();
    }
    
    private void carregarTabela() {
        
        DefaultTableModel tabela = (DefaultTableModel) tbl_Pessoas.getModel();
        
        tabela.setRowCount(0);
        
        for (Pessoa p : listaPessoas) {
            tabela.addRow(p.obterDados());
        }
                
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrp_Sexo = new javax.swing.ButtonGroup();
        txaArea = new javax.swing.JTextField();
        rdo_Masculino = new javax.swing.JRadioButton();
        rdo_Feminino = new javax.swing.JRadioButton();
        lblNome = new javax.swing.JLabel();
        lblSexo = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        chk_Tecnologia = new javax.swing.JCheckBox();
        lblInteresses = new javax.swing.JLabel();
        chk_Astronomia = new javax.swing.JCheckBox();
        chk_Esportes = new javax.swing.JCheckBox();
        cmb_Idioma = new javax.swing.JComboBox<>();
        lblIdioma = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_Pessoas = new javax.swing.JTable();
        btnExcluir = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txaArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txaAreaActionPerformed(evt);
            }
        });

        btnGrp_Sexo.add(rdo_Masculino);
        rdo_Masculino.setForeground(new java.awt.Color(0, 153, 255));
        rdo_Masculino.setText("Masculino");
        rdo_Masculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_MasculinoActionPerformed(evt);
            }
        });

        btnGrp_Sexo.add(rdo_Feminino);
        rdo_Feminino.setForeground(new java.awt.Color(255, 0, 255));
        rdo_Feminino.setText("Feminino");
        rdo_Feminino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_FemininoActionPerformed(evt);
            }
        });

        lblNome.setText("Nome:");

        lblSexo.setText("Sexo:");

        btnSalvar.setText("Salvar");
        btnSalvar.setToolTipText("");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        chk_Tecnologia.setText("Tecnologia");

        lblInteresses.setText("Interesses");

        chk_Astronomia.setText("Astronomia");

        chk_Esportes.setText("Esportes");

        cmb_Idioma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Espanhol", "Inglês", "Português", " " }));

        lblIdioma.setText("Lingua:");

        tbl_Pessoas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Sexo", "Idioma"
            }
        ));
        jScrollPane2.setViewportView(tbl_Pessoas);

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblNome)
                                .addComponent(lblSexo))
                            .addGap(40, 40, 40)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(rdo_Masculino)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(rdo_Feminino))
                                .addComponent(txaArea, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblInteresses)
                                .addComponent(lblIdioma))
                            .addGap(24, 24, 24)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cmb_Idioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(chk_Tecnologia)
                                    .addGap(29, 29, 29)
                                    .addComponent(chk_Astronomia)
                                    .addGap(18, 18, 18)
                                    .addComponent(chk_Esportes)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalvar))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txaArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdo_Masculino)
                    .addComponent(rdo_Feminino)
                    .addComponent(lblSexo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInteresses)
                    .addComponent(chk_Tecnologia)
                    .addComponent(chk_Astronomia)
                    .addComponent(chk_Esportes))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdioma)
                    .addComponent(cmb_Idioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnExcluir)
                    .addComponent(btnEditar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txaAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txaAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txaAreaActionPerformed

    private void rdo_MasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_MasculinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdo_MasculinoActionPerformed

    private void rdo_FemininoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_FemininoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdo_FemininoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:      
        if(rdo_Masculino.isSelected()){
            sexo = 'M';
            JOptionPane.showMessageDialog(null, "Sexo selecionado","Alerta!", JOptionPane.OK_OPTION );
        }
        else if (rdo_Feminino.isSelected()){
            sexo = 'F';
            JOptionPane.showMessageDialog(null, "Sexo selecionado","Alerta!", JOptionPane.OK_OPTION );
        }
        else{
            JOptionPane.showMessageDialog(null, "Selecione um sexo","ERRO!", JOptionPane.OK_OPTION );
            return;
        }
        
        tecnologia = chk_Tecnologia.isSelected();
        astronomia = chk_Astronomia.isSelected();
        esportes = chk_Esportes.isSelected();
        
        JOptionPane.showMessageDialog(null, "Tecnologia " + tecnologia 
                + "\nAstronomia " + astronomia 
                + "\nEsportes " + esportes 
                + "\n", "Alerta!", JOptionPane.INFORMATION_MESSAGE);
        
        
        // criação do objeto Pessoa
        String idioma = cmb_Idioma.getSelectedItem() + "";
        Pessoa p = new Pessoa (txaArea.getText(), sexo, (String) cmb_Idioma.getSelectedItem());
        
        if (linhaEdicao == -1){
            listaPessoas.add(p);
        }
        else {
            listaPessoas.set(linhaEdicao, p);
            linhaEdicao = -1;
        }
        
        arquivo.gravarArquivo();
        carregarTabela();
        JOptionPane .showMessageDialog(
                null,
                "Dados salvos com sucesso!"
        );
        
        // limpa os campos do formulário
        txaArea.setText("");
        btnGrp_Sexo.clearSelection();
        chk_Tecnologia.setSelected(false);
        chk_Astronomia.setSelected(false);
        chk_Esportes.setSelected(false);
        cmb_Idioma.setSelectedIndex(0);
        
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        int linha = tbl_Pessoas.getSelectedRow();
        
        if (linha == -1){
            JOptionPane.showMessageDialog(
                    null,
                    "Selecione uma opção na tabela.",
                    "Atenção",
                    JOptionPane.WARNING_MESSAGE
            );
            
            return;
        }
        
        int resposta = JOptionPane.showConfirmDialog(
                null,
                "Deseja realmente excluir esta pessoa?",
                "Confirmação",
                JOptionPane.YES_NO_OPTION
        );
        
        if (resposta == JOptionPane.YES_OPTION) {
            listaPessoas.remove (linha);
            
            arquivo.gravarArquivo();
            
            DefaultTableModel tabela
                    = (DefaultTableModel) tbl_Pessoas.getModel();
            
            tabela.removeRow(linha);
            
            System.out.println("Pessoa excluida!");
                    
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        int linha = tbl_Pessoas.getSelectedRow();
        
        if (linha == -1) {
            JOptionPane.showMessageDialog(
                    null,
                    "Selecione uma pessoa para editar."
            );
            
            return;
        }
        
        linhaEdicao = linha;
        Pessoa p = listaPessoas.get(linha);
        txaArea.setText(p.nome);
        
        if (p.sexo == 'M') {
            rdo_Masculino.setSelected(true);
        } 
        else {
            rdo_Feminino.setSelected(true);
        }
        
        cmb_Idioma.setSelectedItem(p.idioma);
    }//GEN-LAST:event_btnEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormProjeto04().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.ButtonGroup btnGrp_Sexo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JCheckBox chk_Astronomia;
    private javax.swing.JCheckBox chk_Esportes;
    private javax.swing.JCheckBox chk_Tecnologia;
    private javax.swing.JComboBox<String> cmb_Idioma;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblIdioma;
    private javax.swing.JLabel lblInteresses;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JRadioButton rdo_Feminino;
    private javax.swing.JRadioButton rdo_Masculino;
    private javax.swing.JTable tbl_Pessoas;
    private javax.swing.JTextField txaArea;
    // End of variables declaration//GEN-END:variables
}
