/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gerenciadorbiblioteca;

import java.util.List;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.EXIT_ON_CLOSE;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author laboratorio
 */
public class LivroForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LivroForm.class.getName());
    
    
    private Arquivo arquivo;
    private List<Livro> listaLivros;
    
    // controle
    private int linhaEdicao = -1;


    /**
     * Creates new form LivroForm
     */
    public LivroForm() {
        initComponents();
        arquivo = new Arquivo("livros");
        listaLivros = arquivo.lerArquivo();
        atualizarTabela();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTitulo = new javax.swing.JTextField();
        lblTituloLivro = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblAutor = new javax.swing.JLabel();
        txtAutor = new javax.swing.JTextField();
        lblAnoPublicacao = new javax.swing.JLabel();
        txtAnoPublicacao = new javax.swing.JTextField();
        lblTipo = new javax.swing.JLabel();
        rdo_Fisico = new javax.swing.JRadioButton();
        rdo_Digital = new javax.swing.JRadioButton();
        cmb_Categoria = new javax.swing.JComboBox<>();
        lblCategoria = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        rdo_NaoIniciado = new javax.swing.JRadioButton();
        rdo_Concluido = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLivros = new javax.swing.JTable();
        btnSalvar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTituloActionPerformed(evt);
            }
        });

        lblTituloLivro.setText("Informe o titulo:");

        lblTitulo.setText("Cadastro de Livros");

        lblAutor.setText("Informe o autor:");

        txtAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAutorActionPerformed(evt);
            }
        });

        lblAnoPublicacao.setText("Ano de publicação:");

        txtAnoPublicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnoPublicacaoActionPerformed(evt);
            }
        });

        lblTipo.setText("Tipo do livro:");

        rdo_Fisico.setText("Físico");
        rdo_Fisico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_FisicoActionPerformed(evt);
            }
        });

        rdo_Digital.setText("Digital");
        rdo_Digital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_DigitalActionPerformed(evt);
            }
        });

        cmb_Categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tecnologia", "Ficção", "Romance", "História" }));

        lblCategoria.setText("Categoria do Livro:");

        lblStatus.setText("Status de leitura:");

        rdo_NaoIniciado.setText("Não iniciado");

        rdo_Concluido.setText("Concluído");

        tblLivros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Titulo", "Autor", "Ano", "Tipo", "Categoria", "Status"
            }
        ));
        tblLivros.setToolTipText("");
        jScrollPane1.setViewportView(tblLivros);

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnEditar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSalvar))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblAutor, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblTituloLivro)
                                            .addGap(9, 9, 9)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtAutor, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                                        .addComponent(txtTitulo)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblAnoPublicacao)
                                        .addComponent(lblTipo)
                                        .addComponent(lblCategoria)
                                        .addComponent(lblStatus))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtAnoPublicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cmb_Categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(rdo_Fisico)
                                            .addGap(56, 56, 56)
                                            .addComponent(rdo_Digital))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(rdo_NaoIniciado)
                                            .addGap(18, 18, 18)
                                            .addComponent(rdo_Concluido)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(lblTitulo)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitulo)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTituloLivro))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAutor)
                    .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAnoPublicacao)
                    .addComponent(txtAnoPublicacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipo)
                    .addComponent(rdo_Fisico)
                    .addComponent(rdo_Digital))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_Categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCategoria))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatus)
                    .addComponent(rdo_NaoIniciado)
                    .addComponent(rdo_Concluido))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnEditar))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloActionPerformed

    private void txtAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAutorActionPerformed

    private void txtAnoPublicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnoPublicacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnoPublicacaoActionPerformed

    private void rdo_FisicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_FisicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdo_FisicoActionPerformed

    private void rdo_DigitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_DigitalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdo_DigitalActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        
        String titulo = txtTitulo.getText();
        String autor = txtAutor.getText();
        int anoPublicacao = Integer.parseInt(txtAnoPublicacao.getText().trim());
        String tipo = rdo_Fisico.isSelected() ? "Fisico" : "Digital";
        String categorias = cmb_Categoria.getSelectedItem().toString(); 
        String status = rdo_NaoIniciado.isSelected() ? "Não inicidado" : "Concluido";
        
        
        Livro l = new Livro(titulo, autor, anoPublicacao, tipo, categorias, status);

        if (linhaEdicao == -1) {
            listaLivros.add(l);
        } else {
 
            listaLivros.set(linhaEdicao, l);
            linhaEdicao = -1; 
        }

        arquivo.gravarArquivo(listaLivros);

        atualizarTabela();
     
        limparFormulario();


    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        
        int linha = tblLivros.getSelectedRow();

        if (linha == -1) {
            JOptionPane.showMessageDialog(null, "Selecione um livro para editar!",
                    "Atencao", JOptionPane.WARNING_MESSAGE);
            return;
        }

        linhaEdicao = linha;

        Livro l = listaLivros.get(linha);

        txtTitulo.setText(l.getTitulo());
        txtAutor.setText(l.getAutor());
        txtAnoPublicacao.setText(String.valueOf(l.getAnoPublicacao()));

        txtTitulo.requestFocus();
    }//GEN-LAST:event_btnEditarActionPerformed
    
    private void atualizarTabela() {
        DefaultTableModel modelo = (DefaultTableModel) tblLivros.getModel();
        modelo.setRowCount(0);

        for (Livro l : listaLivros) {
            modelo.addRow(new Object[]{
                l.getTitulo(),
                l.getAutor(),
                l.getAnoPublicacao(),
                l.getTipo(),
                l.getCategorias(),
                l.getStatus(),
            });
        }
    }
    
    private void limparFormulario() {
        txtTitulo.setText("");
        txtAutor.setText("");
        txtAnoPublicacao.setText("");
        cmb_Categoria.setSelectedIndex(0);
        rdo_NaoIniciado.setSelected(false);
        rdo_Concluido.setSelected(false);
        linhaEdicao = -1;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LivroForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cmb_Categoria;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAnoPublicacao;
    private javax.swing.JLabel lblAutor;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTituloLivro;
    private javax.swing.JRadioButton rdo_Concluido;
    private javax.swing.JRadioButton rdo_Digital;
    private javax.swing.JRadioButton rdo_Fisico;
    private javax.swing.JRadioButton rdo_NaoIniciado;
    private javax.swing.JTable tblLivros;
    private javax.swing.JTextField txtAnoPublicacao;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
